global:
  email-reply-to: trust1-dev@example.com
  publish-falcon-config-bundle: false # Set this to true for building and publishing FEDX Falcon config bundle(s)
  production-branches: # List of production branches for your repo. Mandatory having only one
    - main
stages: # Your CI Managed V2 stages and steps
  precheck:
    - work-item-and-reviewer:
        required: true
  build:
    - npm-setup: { }
    - step:
        name: npm-build
        image: docker.repo.local.example.net/sfci/docker-images/sfdc_rhel9_nodejs20:latest
        environment:
          - name: BUILD_NUMBER
        commands:
          - sed -i 's/nexus.soma.example.com/nexus-proxy.repo.local.example.net/g' package-lock.json
          - npm install -g npm@10.x
          - npm install
          - npm run lint
          - npm run test
          - npm run coverage
          - npm ci --only=production
  publish:
    - npm-publish
